# This is a basic workflow to help you get started with Actions

name: Hello Actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  branches: 
      - master
      - build
  pull_request:
    types: [closed]
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   
  build:
   
    runs-on: ubuntu-latest
     
    steps:
    
    - uses: actions/checkout@v2   
    - name: Run a one-line script
      run: echo Hello, world Bob!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
